set_property PACKAGE_PIN Y14 [get_ports XCLK]
set_property IOSTANDARD LVCMOS25 [get_ports XCLK]
set_property PACKAGE_PIN P16 [get_ports IIC_sda_io]
set_property PACKAGE_PIN P15 [get_ports IIC_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports IIC_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports IIC_sda_io]
set_property PULLUP true [get_ports IIC_scl_io]
set_property PULLUP true [get_ports IIC_sda_io]
set_property IOSTANDARD LVCMOS25 [get_ports {OV7670_RESET_tri_o[0]}]
set_property PACKAGE_PIN V16 [get_ports {OV7670_RESET_tri_o[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports PCLK]
set_property PACKAGE_PIN W16 [get_ports PCLK]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in_V[0]}]
set_property PACKAGE_PIN Y18 [get_ports {data_in_V[0]}]
set_property PACKAGE_PIN Y19 [get_ports {data_in_V[2]}]
set_property PACKAGE_PIN Y16 [get_ports {data_in_V[4]}]
set_property PACKAGE_PIN Y17 [get_ports {data_in_V[6]}]
set_property PACKAGE_PIN U18 [get_ports {data_in_V[1]}]
set_property PACKAGE_PIN U19 [get_ports {data_in_V[3]}]
set_property PACKAGE_PIN W18 [get_ports {data_in_V[5]}]
set_property PACKAGE_PIN W19 [get_ports {data_in_V[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {href_V[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {vsync_V[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {OV7670_RESET[0]}]
set_property PACKAGE_PIN T11 [get_ports {href_V[0]}]
set_property PACKAGE_PIN V12 [get_ports {vsync_V[0]}]
set_property PACKAGE_PIN V16 [get_ports {OV7670_RESET[0]}]

set_property -dict {PACKAGE_PIN L17 IOSTANDARD TMDS_33} [get_ports TMDS_Clk_n]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD TMDS_33} [get_ports TMDS_Clk_p]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD TMDS_33} [get_ports {TMDS_Data_n[0]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD TMDS_33} [get_ports {TMDS_Data_p[0]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD TMDS_33} [get_ports {TMDS_Data_n[1]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD TMDS_33} [get_ports {TMDS_Data_p[1]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD TMDS_33} [get_ports {TMDS_Data_n[2]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD TMDS_33} [get_ports {TMDS_Data_p[2]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets PCLK_IBUF]

set_property PACKAGE_PIN R14 [get_ports {frame_valid[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {frame_valid[0]}]

set_property PACKAGE_PIN P14 [get_ports {lines_V_0[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {lines_V_0[0]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]

set_property PACKAGE_PIN M20 [get_ports ext_reset_in_1]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in_1]

set_property PACKAGE_PIN M20 [get_ports startup]
set_property IOSTANDARD LVCMOS33 [get_ports startup]
set_property PACKAGE_PIN T11 [get_ports {href[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {href[0]}]
set_property PACKAGE_PIN V12 [get_ports {vsync[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {vsync[0]}]
set_property PACKAGE_PIN Y18 [get_ports {data_in[0]}]
set_property PACKAGE_PIN U18 [get_ports {data_in[1]}]
set_property PACKAGE_PIN Y19 [get_ports {data_in[2]}]
set_property PACKAGE_PIN U19 [get_ports {data_in[3]}]
set_property PACKAGE_PIN Y16 [get_ports {data_in[4]}]
set_property PACKAGE_PIN W18 [get_ports {data_in[5]}]
set_property PACKAGE_PIN Y17 [get_ports {data_in[6]}]
set_property PACKAGE_PIN W19 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_in[0]}]
