// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _scaleImage_HH_
#define _scaleImage_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_proc.h"
#include "AXIvideo2Mat.h"
#include "Resize.h"
#include "Mat2AXIvideo.h"
#include "fifo_w10_d2_A.h"
#include "fifo_w11_d2_A.h"
#include "fifo_w11_d3_A.h"
#include "fifo_w8_d2_A.h"
#include "start_for_Resize_U0.h"
#include "start_for_Mat2AXIhbi.h"

namespace ap_rtl {

struct scaleImage : public sc_module {
    // Port declarations 24
    sc_in< sc_lv<8> > inStream_TDATA;
    sc_in< sc_lv<1> > inStream_TKEEP;
    sc_in< sc_lv<1> > inStream_TSTRB;
    sc_in< sc_lv<1> > inStream_TUSER;
    sc_in< sc_lv<1> > inStream_TLAST;
    sc_in< sc_lv<1> > inStream_TID;
    sc_in< sc_lv<1> > inStream_TDEST;
    sc_out< sc_lv<8> > outStream_TDATA;
    sc_out< sc_lv<1> > outStream_TKEEP;
    sc_out< sc_lv<1> > outStream_TSTRB;
    sc_out< sc_lv<1> > outStream_TUSER;
    sc_out< sc_lv<1> > outStream_TLAST;
    sc_out< sc_lv<1> > outStream_TID;
    sc_out< sc_lv<1> > outStream_TDEST;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > inStream_TVALID;
    sc_out< sc_logic > inStream_TREADY;
    sc_out< sc_logic > outStream_TVALID;
    sc_in< sc_logic > outStream_TREADY;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    scaleImage(sc_module_name name);
    SC_HAS_PROCESS(scaleImage);

    ~scaleImage();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    Block_proc* Block_proc_U0;
    AXIvideo2Mat* AXIvideo2Mat_U0;
    Resize* Resize_U0;
    Mat2AXIvideo* Mat2AXIvideo_U0;
    fifo_w10_d2_A* inImage_rows_V_c_U;
    fifo_w11_d2_A* inImage_cols_V_c_U;
    fifo_w11_d3_A* outImage_rows_V_c_U;
    fifo_w11_d3_A* outImage_cols_V_c_U;
    fifo_w8_d2_A* inImage_data_stream_s_U;
    fifo_w10_d2_A* inImage_rows_V_c8_U;
    fifo_w11_d2_A* inImage_cols_V_c9_U;
    fifo_w8_d2_A* outImage_data_stream_U;
    fifo_w11_d2_A* outImage_rows_V_c10_U;
    fifo_w11_d2_A* outImage_cols_V_c11_U;
    start_for_Resize_U0* start_for_Resize_U0_U;
    start_for_Mat2AXIhbi* start_for_Mat2AXIhbi_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > Block_proc_U0_ap_start;
    sc_signal< sc_logic > Block_proc_U0_ap_done;
    sc_signal< sc_logic > Block_proc_U0_ap_continue;
    sc_signal< sc_logic > Block_proc_U0_ap_idle;
    sc_signal< sc_logic > Block_proc_U0_ap_ready;
    sc_signal< sc_logic > Block_proc_U0_start_out;
    sc_signal< sc_logic > Block_proc_U0_start_write;
    sc_signal< sc_lv<10> > Block_proc_U0_inImage_rows_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_inImage_rows_V_out_write;
    sc_signal< sc_lv<11> > Block_proc_U0_inImage_cols_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_inImage_cols_V_out_write;
    sc_signal< sc_lv<11> > Block_proc_U0_outImage_rows_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_outImage_rows_V_out_write;
    sc_signal< sc_lv<11> > Block_proc_U0_outImage_cols_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_outImage_cols_V_out_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_start;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_done;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_continue;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_idle;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > AXIvideo2Mat_U0_inStream_TREADY;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_read;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_V_write;
    sc_signal< sc_lv<10> > AXIvideo2Mat_U0_img_rows_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_out_write;
    sc_signal< sc_lv<11> > AXIvideo2Mat_U0_img_cols_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_out_write;
    sc_signal< sc_logic > Resize_U0_ap_start;
    sc_signal< sc_logic > Resize_U0_ap_done;
    sc_signal< sc_logic > Resize_U0_ap_continue;
    sc_signal< sc_logic > Resize_U0_ap_idle;
    sc_signal< sc_logic > Resize_U0_ap_ready;
    sc_signal< sc_logic > Resize_U0_start_out;
    sc_signal< sc_logic > Resize_U0_start_write;
    sc_signal< sc_logic > Resize_U0_p_src_rows_V_read;
    sc_signal< sc_logic > Resize_U0_p_src_cols_V_read;
    sc_signal< sc_logic > Resize_U0_p_src_data_stream_V_read;
    sc_signal< sc_logic > Resize_U0_p_dst_rows_V_read;
    sc_signal< sc_logic > Resize_U0_p_dst_cols_V_read;
    sc_signal< sc_lv<8> > Resize_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > Resize_U0_p_dst_data_stream_V_write;
    sc_signal< sc_lv<11> > Resize_U0_p_dst_rows_V_out_din;
    sc_signal< sc_logic > Resize_U0_p_dst_rows_V_out_write;
    sc_signal< sc_lv<11> > Resize_U0_p_dst_cols_V_out_din;
    sc_signal< sc_logic > Resize_U0_p_dst_cols_V_out_write;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_start;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_done;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_continue;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_idle;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_ready;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_rows_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_cols_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_V_read;
    sc_signal< sc_lv<8> > Mat2AXIvideo_U0_outStream_TDATA;
    sc_signal< sc_logic > Mat2AXIvideo_U0_outStream_TVALID;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_outStream_TKEEP;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_outStream_TSTRB;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_outStream_TUSER;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_outStream_TLAST;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_outStream_TID;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_outStream_TDEST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > inImage_rows_V_c_full_n;
    sc_signal< sc_lv<10> > inImage_rows_V_c_dout;
    sc_signal< sc_logic > inImage_rows_V_c_empty_n;
    sc_signal< sc_logic > inImage_cols_V_c_full_n;
    sc_signal< sc_lv<11> > inImage_cols_V_c_dout;
    sc_signal< sc_logic > inImage_cols_V_c_empty_n;
    sc_signal< sc_logic > outImage_rows_V_c_full_n;
    sc_signal< sc_lv<11> > outImage_rows_V_c_dout;
    sc_signal< sc_logic > outImage_rows_V_c_empty_n;
    sc_signal< sc_logic > outImage_cols_V_c_full_n;
    sc_signal< sc_lv<11> > outImage_cols_V_c_dout;
    sc_signal< sc_logic > outImage_cols_V_c_empty_n;
    sc_signal< sc_logic > inImage_data_stream_s_full_n;
    sc_signal< sc_lv<8> > inImage_data_stream_s_dout;
    sc_signal< sc_logic > inImage_data_stream_s_empty_n;
    sc_signal< sc_logic > inImage_rows_V_c8_full_n;
    sc_signal< sc_lv<10> > inImage_rows_V_c8_dout;
    sc_signal< sc_logic > inImage_rows_V_c8_empty_n;
    sc_signal< sc_logic > inImage_cols_V_c9_full_n;
    sc_signal< sc_lv<11> > inImage_cols_V_c9_dout;
    sc_signal< sc_logic > inImage_cols_V_c9_empty_n;
    sc_signal< sc_logic > outImage_data_stream_full_n;
    sc_signal< sc_lv<8> > outImage_data_stream_dout;
    sc_signal< sc_logic > outImage_data_stream_empty_n;
    sc_signal< sc_logic > outImage_rows_V_c10_full_n;
    sc_signal< sc_lv<11> > outImage_rows_V_c10_dout;
    sc_signal< sc_logic > outImage_rows_V_c10_empty_n;
    sc_signal< sc_logic > outImage_cols_V_c11_full_n;
    sc_signal< sc_lv<11> > outImage_cols_V_c11_dout;
    sc_signal< sc_logic > outImage_cols_V_c11_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Block_proc_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_proc_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_proc_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_lv<2> > AXIvideo2Mat_U0_ap_ready_count;
    sc_signal< sc_lv<1> > start_for_Resize_U0_din;
    sc_signal< sc_logic > start_for_Resize_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Resize_U0_dout;
    sc_signal< sc_logic > start_for_Resize_U0_empty_n;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_full_n;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_write;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_din;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_dout;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_empty_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_full_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_write;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_AXIvideo2Mat_U0_ap_continue();
    void thread_AXIvideo2Mat_U0_ap_start();
    void thread_AXIvideo2Mat_U0_start_full_n();
    void thread_AXIvideo2Mat_U0_start_write();
    void thread_Block_proc_U0_ap_continue();
    void thread_Block_proc_U0_ap_start();
    void thread_Mat2AXIvideo_U0_ap_continue();
    void thread_Mat2AXIvideo_U0_ap_start();
    void thread_Mat2AXIvideo_U0_start_full_n();
    void thread_Mat2AXIvideo_U0_start_write();
    void thread_Resize_U0_ap_continue();
    void thread_Resize_U0_ap_start();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_AXIvideo2Mat_U0_ap_ready();
    void thread_ap_sync_Block_proc_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_inStream_TREADY();
    void thread_outStream_TDATA();
    void thread_outStream_TDEST();
    void thread_outStream_TID();
    void thread_outStream_TKEEP();
    void thread_outStream_TLAST();
    void thread_outStream_TSTRB();
    void thread_outStream_TUSER();
    void thread_outStream_TVALID();
    void thread_start_for_Mat2AXIvideo_U0_din();
    void thread_start_for_Resize_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
