// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "AXIvideo2Mat.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic AXIvideo2Mat::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic AXIvideo2Mat::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state1 = "1";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state2 = "10";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state3 = "100";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state4 = "1000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_pp1_stage0 = "10000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state7 = "100000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state8 = "1000000";
const sc_lv<8> AXIvideo2Mat::ap_ST_fsm_state9 = "10000000";
const bool AXIvideo2Mat::ap_const_boolean_1 = true;
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> AXIvideo2Mat::ap_const_lv1_0 = "0";
const sc_lv<1> AXIvideo2Mat::ap_const_lv1_1 = "1";
const sc_lv<2> AXIvideo2Mat::ap_const_lv2_0 = "00";
const sc_lv<2> AXIvideo2Mat::ap_const_lv2_2 = "10";
const sc_lv<2> AXIvideo2Mat::ap_const_lv2_3 = "11";
const sc_lv<2> AXIvideo2Mat::ap_const_lv2_1 = "1";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_1 = "1";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_4 = "100";
const bool AXIvideo2Mat::ap_const_boolean_0 = false;
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_6 = "110";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_3 = "11";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_7 = "111";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_2 = "10";
const sc_lv<32> AXIvideo2Mat::ap_const_lv32_5 = "101";

AXIvideo2Mat::AXIvideo2Mat(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_ack_in);
    sensitive << ( AXI_video_strm_V_data_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_data_out);
    sensitive << ( AXI_video_strm_V_data_V_0_payload_A );
    sensitive << ( AXI_video_strm_V_data_V_0_payload_B );
    sensitive << ( AXI_video_strm_V_data_V_0_sel );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_load_A);
    sensitive << ( AXI_video_strm_V_data_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_load_B);
    sensitive << ( AXI_video_strm_V_data_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_data_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_sel);
    sensitive << ( AXI_video_strm_V_data_V_0_sel_rd );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_state_cmp_full);
    sensitive << ( AXI_video_strm_V_data_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_vld_in);
    sensitive << ( inStream_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_data_V_0_vld_out);
    sensitive << ( AXI_video_strm_V_data_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_dest_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_AXI_video_strm_V_dest_V_0_vld_in);
    sensitive << ( inStream_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_ack_in);
    sensitive << ( AXI_video_strm_V_last_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_data_out);
    sensitive << ( AXI_video_strm_V_last_V_0_payload_A );
    sensitive << ( AXI_video_strm_V_last_V_0_payload_B );
    sensitive << ( AXI_video_strm_V_last_V_0_sel );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_load_A);
    sensitive << ( AXI_video_strm_V_last_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_last_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_load_B);
    sensitive << ( AXI_video_strm_V_last_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_last_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_sel);
    sensitive << ( AXI_video_strm_V_last_V_0_sel_rd );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_state_cmp_full);
    sensitive << ( AXI_video_strm_V_last_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_vld_in);
    sensitive << ( inStream_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_last_V_0_vld_out);
    sensitive << ( AXI_video_strm_V_last_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_ack_in);
    sensitive << ( AXI_video_strm_V_user_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_ack_out);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_predicate_op65_read_state5 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_data_out);
    sensitive << ( AXI_video_strm_V_user_V_0_payload_A );
    sensitive << ( AXI_video_strm_V_user_V_0_payload_B );
    sensitive << ( AXI_video_strm_V_user_V_0_sel );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_load_A);
    sensitive << ( AXI_video_strm_V_user_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_user_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_load_B);
    sensitive << ( AXI_video_strm_V_user_V_0_sel_wr );
    sensitive << ( AXI_video_strm_V_user_V_0_state_cmp_full );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_sel);
    sensitive << ( AXI_video_strm_V_user_V_0_sel_rd );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_state_cmp_full);
    sensitive << ( AXI_video_strm_V_user_V_0_state );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_vld_in);
    sensitive << ( inStream_TVALID );

    SC_METHOD(thread_AXI_video_strm_V_user_V_0_vld_out);
    sensitive << ( AXI_video_strm_V_user_V_0_state );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_01001);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_pp1_stage0_11001);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_ap_block_state5_pp1_stage0_iter0);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( ap_predicate_op65_read_state5 );

    SC_METHOD(thread_ap_block_state6_pp1_stage0_iter1);
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( icmp_ln73_reg_433 );

    SC_METHOD(thread_ap_block_state8);
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_ap_condition_582);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state5);
    sensitive << ( icmp_ln73_fu_369_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln71_fu_358_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( axi_data_V_1_i_reg_237 );
    sensitive << ( p_Val2_s_reg_284 );

    SC_METHOD(thread_ap_phi_mux_eol_0_i_phi_fu_263_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( eol_0_i_reg_259 );
    sensitive << ( axi_last_V_2_i_reg_271 );

    SC_METHOD(thread_ap_phi_mux_eol_2_i_phi_fu_324_p4);
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_ap_phi_mux_eol_phi_fu_229_p4);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( eol_reg_226 );
    sensitive << ( axi_last_V_2_i_reg_271 );

    SC_METHOD(thread_ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_271);

    SC_METHOD(thread_ap_phi_reg_pp1_iter0_p_Val2_s_reg_284);

    SC_METHOD(thread_ap_predicate_op65_read_state5);
    sensitive << ( icmp_ln73_fu_369_p2 );
    sensitive << ( or_ln76_fu_383_p2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_cols_V_fu_345_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_cols_V_dout );

    SC_METHOD(thread_cols_V_fu_345_p1);
    sensitive << ( cols_V_fu_345_p0 );

    SC_METHOD(thread_i_V_fu_363_p2);
    sensitive << ( t_V_reg_215 );

    SC_METHOD(thread_icmp_ln71_fu_358_p2);
    sensitive << ( rows_V_reg_394 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( t_V_reg_215 );

    SC_METHOD(thread_icmp_ln73_fu_369_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( t_V_2_reg_248 );
    sensitive << ( cols_V_reg_399 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_img_cols_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_cols_V_empty_n );

    SC_METHOD(thread_img_cols_V_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_cols_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_dout );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_cols_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_cols_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_data_stream_V_blk_n);
    sensitive << ( img_data_stream_V_full_n );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );

    SC_METHOD(thread_img_data_stream_V_din);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( p_Val2_s_reg_284 );
    sensitive << ( ap_block_pp1_stage0_01001 );

    SC_METHOD(thread_img_data_stream_V_write);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln73_reg_433 );
    sensitive << ( ap_block_pp1_stage0_11001 );

    SC_METHOD(thread_img_rows_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_empty_n );

    SC_METHOD(thread_img_rows_V_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_out_full_n );

    SC_METHOD(thread_img_rows_V_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_dout );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_rows_V_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_img_rows_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );

    SC_METHOD(thread_inStream_TDATA_blk_n);
    sensitive << ( AXI_video_strm_V_data_V_0_state );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( icmp_ln73_fu_369_p2 );
    sensitive << ( or_ln76_fu_383_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( eol_2_i_reg_321 );

    SC_METHOD(thread_inStream_TREADY);
    sensitive << ( AXI_video_strm_V_dest_V_0_state );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( icmp_ln71_fu_358_p2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_j_V_fu_374_p2);
    sensitive << ( t_V_2_reg_248 );

    SC_METHOD(thread_or_ln76_fu_383_p2);
    sensitive << ( ap_phi_mux_eol_0_i_phi_fu_263_p4 );
    sensitive << ( sof_1_i_fu_138 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_rows_V_fu_341_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_rows_V_dout );

    SC_METHOD(thread_rows_V_fu_341_p1);
    sensitive << ( rows_V_fu_341_p0 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_user_V_fu_349_p1);
    sensitive << ( AXI_video_strm_V_user_V_0_data_out );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( AXI_video_strm_V_data_V_0_vld_out );
    sensitive << ( img_rows_V_empty_n );
    sensitive << ( img_cols_V_empty_n );
    sensitive << ( img_rows_V_out_full_n );
    sensitive << ( img_cols_V_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( icmp_ln73_fu_369_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_phi_mux_eol_2_i_phi_fu_324_p4 );
    sensitive << ( icmp_ln71_fu_358_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( eol_2_i_reg_321 );
    sensitive << ( tmp_user_V_fu_349_p1 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    AXI_video_strm_V_data_V_0_sel_rd = SC_LOGIC_0;
    AXI_video_strm_V_data_V_0_sel_wr = SC_LOGIC_0;
    AXI_video_strm_V_data_V_0_state = "00";
    AXI_video_strm_V_user_V_0_sel_rd = SC_LOGIC_0;
    AXI_video_strm_V_user_V_0_sel_wr = SC_LOGIC_0;
    AXI_video_strm_V_user_V_0_state = "00";
    AXI_video_strm_V_last_V_0_sel_rd = SC_LOGIC_0;
    AXI_video_strm_V_last_V_0_sel_wr = SC_LOGIC_0;
    AXI_video_strm_V_last_V_0_state = "00";
    AXI_video_strm_V_dest_V_0_state = "00";
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "AXIvideo2Mat_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, inStream_TDATA, "(port)inStream_TDATA");
    sc_trace(mVcdFile, inStream_TVALID, "(port)inStream_TVALID");
    sc_trace(mVcdFile, inStream_TREADY, "(port)inStream_TREADY");
    sc_trace(mVcdFile, inStream_TKEEP, "(port)inStream_TKEEP");
    sc_trace(mVcdFile, inStream_TSTRB, "(port)inStream_TSTRB");
    sc_trace(mVcdFile, inStream_TUSER, "(port)inStream_TUSER");
    sc_trace(mVcdFile, inStream_TLAST, "(port)inStream_TLAST");
    sc_trace(mVcdFile, inStream_TID, "(port)inStream_TID");
    sc_trace(mVcdFile, inStream_TDEST, "(port)inStream_TDEST");
    sc_trace(mVcdFile, img_rows_V_dout, "(port)img_rows_V_dout");
    sc_trace(mVcdFile, img_rows_V_empty_n, "(port)img_rows_V_empty_n");
    sc_trace(mVcdFile, img_rows_V_read, "(port)img_rows_V_read");
    sc_trace(mVcdFile, img_cols_V_dout, "(port)img_cols_V_dout");
    sc_trace(mVcdFile, img_cols_V_empty_n, "(port)img_cols_V_empty_n");
    sc_trace(mVcdFile, img_cols_V_read, "(port)img_cols_V_read");
    sc_trace(mVcdFile, img_data_stream_V_din, "(port)img_data_stream_V_din");
    sc_trace(mVcdFile, img_data_stream_V_full_n, "(port)img_data_stream_V_full_n");
    sc_trace(mVcdFile, img_data_stream_V_write, "(port)img_data_stream_V_write");
    sc_trace(mVcdFile, img_rows_V_out_din, "(port)img_rows_V_out_din");
    sc_trace(mVcdFile, img_rows_V_out_full_n, "(port)img_rows_V_out_full_n");
    sc_trace(mVcdFile, img_rows_V_out_write, "(port)img_rows_V_out_write");
    sc_trace(mVcdFile, img_cols_V_out_din, "(port)img_cols_V_out_din");
    sc_trace(mVcdFile, img_cols_V_out_full_n, "(port)img_cols_V_out_full_n");
    sc_trace(mVcdFile, img_cols_V_out_write, "(port)img_cols_V_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_data_out, "AXI_video_strm_V_data_V_0_data_out");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_vld_in, "AXI_video_strm_V_data_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_vld_out, "AXI_video_strm_V_data_V_0_vld_out");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_ack_in, "AXI_video_strm_V_data_V_0_ack_in");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_ack_out, "AXI_video_strm_V_data_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_payload_A, "AXI_video_strm_V_data_V_0_payload_A");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_payload_B, "AXI_video_strm_V_data_V_0_payload_B");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_sel_rd, "AXI_video_strm_V_data_V_0_sel_rd");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_sel_wr, "AXI_video_strm_V_data_V_0_sel_wr");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_sel, "AXI_video_strm_V_data_V_0_sel");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_load_A, "AXI_video_strm_V_data_V_0_load_A");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_load_B, "AXI_video_strm_V_data_V_0_load_B");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_state, "AXI_video_strm_V_data_V_0_state");
    sc_trace(mVcdFile, AXI_video_strm_V_data_V_0_state_cmp_full, "AXI_video_strm_V_data_V_0_state_cmp_full");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_data_out, "AXI_video_strm_V_user_V_0_data_out");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_vld_in, "AXI_video_strm_V_user_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_vld_out, "AXI_video_strm_V_user_V_0_vld_out");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_ack_in, "AXI_video_strm_V_user_V_0_ack_in");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_ack_out, "AXI_video_strm_V_user_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_payload_A, "AXI_video_strm_V_user_V_0_payload_A");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_payload_B, "AXI_video_strm_V_user_V_0_payload_B");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_sel_rd, "AXI_video_strm_V_user_V_0_sel_rd");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_sel_wr, "AXI_video_strm_V_user_V_0_sel_wr");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_sel, "AXI_video_strm_V_user_V_0_sel");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_load_A, "AXI_video_strm_V_user_V_0_load_A");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_load_B, "AXI_video_strm_V_user_V_0_load_B");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_state, "AXI_video_strm_V_user_V_0_state");
    sc_trace(mVcdFile, AXI_video_strm_V_user_V_0_state_cmp_full, "AXI_video_strm_V_user_V_0_state_cmp_full");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_data_out, "AXI_video_strm_V_last_V_0_data_out");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_vld_in, "AXI_video_strm_V_last_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_vld_out, "AXI_video_strm_V_last_V_0_vld_out");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_ack_in, "AXI_video_strm_V_last_V_0_ack_in");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_ack_out, "AXI_video_strm_V_last_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_payload_A, "AXI_video_strm_V_last_V_0_payload_A");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_payload_B, "AXI_video_strm_V_last_V_0_payload_B");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_sel_rd, "AXI_video_strm_V_last_V_0_sel_rd");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_sel_wr, "AXI_video_strm_V_last_V_0_sel_wr");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_sel, "AXI_video_strm_V_last_V_0_sel");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_load_A, "AXI_video_strm_V_last_V_0_load_A");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_load_B, "AXI_video_strm_V_last_V_0_load_B");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_state, "AXI_video_strm_V_last_V_0_state");
    sc_trace(mVcdFile, AXI_video_strm_V_last_V_0_state_cmp_full, "AXI_video_strm_V_last_V_0_state_cmp_full");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_0_vld_in, "AXI_video_strm_V_dest_V_0_vld_in");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_0_ack_out, "AXI_video_strm_V_dest_V_0_ack_out");
    sc_trace(mVcdFile, AXI_video_strm_V_dest_V_0_state, "AXI_video_strm_V_dest_V_0_state");
    sc_trace(mVcdFile, inStream_TDATA_blk_n, "inStream_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, icmp_ln73_fu_369_p2, "icmp_ln73_fu_369_p2");
    sc_trace(mVcdFile, or_ln76_fu_383_p2, "or_ln76_fu_383_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_phi_mux_eol_2_i_phi_fu_324_p4, "ap_phi_mux_eol_2_i_phi_fu_324_p4");
    sc_trace(mVcdFile, img_rows_V_blk_n, "img_rows_V_blk_n");
    sc_trace(mVcdFile, img_cols_V_blk_n, "img_cols_V_blk_n");
    sc_trace(mVcdFile, img_data_stream_V_blk_n, "img_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, icmp_ln73_reg_433, "icmp_ln73_reg_433");
    sc_trace(mVcdFile, img_rows_V_out_blk_n, "img_rows_V_out_blk_n");
    sc_trace(mVcdFile, img_cols_V_out_blk_n, "img_cols_V_out_blk_n");
    sc_trace(mVcdFile, eol_reg_226, "eol_reg_226");
    sc_trace(mVcdFile, axi_data_V_1_i_reg_237, "axi_data_V_1_i_reg_237");
    sc_trace(mVcdFile, t_V_2_reg_248, "t_V_2_reg_248");
    sc_trace(mVcdFile, eol_0_i_reg_259, "eol_0_i_reg_259");
    sc_trace(mVcdFile, axi_last_V_2_i_reg_271, "axi_last_V_2_i_reg_271");
    sc_trace(mVcdFile, p_Val2_s_reg_284, "p_Val2_s_reg_284");
    sc_trace(mVcdFile, rows_V_fu_341_p1, "rows_V_fu_341_p1");
    sc_trace(mVcdFile, rows_V_reg_394, "rows_V_reg_394");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, cols_V_fu_345_p1, "cols_V_fu_345_p1");
    sc_trace(mVcdFile, cols_V_reg_399, "cols_V_reg_399");
    sc_trace(mVcdFile, tmp_data_V_reg_404, "tmp_data_V_reg_404");
    sc_trace(mVcdFile, tmp_last_V_reg_412, "tmp_last_V_reg_412");
    sc_trace(mVcdFile, icmp_ln71_fu_358_p2, "icmp_ln71_fu_358_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i_V_fu_363_p2, "i_V_fu_363_p2");
    sc_trace(mVcdFile, i_V_reg_428, "i_V_reg_428");
    sc_trace(mVcdFile, ap_predicate_op65_read_state5, "ap_predicate_op65_read_state5");
    sc_trace(mVcdFile, ap_block_state5_pp1_stage0_iter0, "ap_block_state5_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp1_stage0_iter1, "ap_block_state6_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, j_V_fu_374_p2, "j_V_fu_374_p2");
    sc_trace(mVcdFile, ap_block_state8, "ap_block_state8");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state5, "ap_condition_pp1_exit_iter0_state5");
    sc_trace(mVcdFile, axi_last_V_3_i_reg_297, "axi_last_V_3_i_reg_297");
    sc_trace(mVcdFile, axi_last_V_0_i_reg_195, "axi_last_V_0_i_reg_195");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, axi_data_V_3_i_reg_309, "axi_data_V_3_i_reg_309");
    sc_trace(mVcdFile, axi_data_V_0_i_reg_205, "axi_data_V_0_i_reg_205");
    sc_trace(mVcdFile, t_V_reg_215, "t_V_reg_215");
    sc_trace(mVcdFile, ap_phi_mux_eol_phi_fu_229_p4, "ap_phi_mux_eol_phi_fu_229_p4");
    sc_trace(mVcdFile, ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4, "ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4");
    sc_trace(mVcdFile, ap_phi_mux_eol_0_i_phi_fu_263_p4, "ap_phi_mux_eol_0_i_phi_fu_263_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_271, "ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_271");
    sc_trace(mVcdFile, ap_phi_reg_pp1_iter0_p_Val2_s_reg_284, "ap_phi_reg_pp1_iter0_p_Val2_s_reg_284");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, eol_2_i_reg_321, "eol_2_i_reg_321");
    sc_trace(mVcdFile, sof_1_i_fu_138, "sof_1_i_fu_138");
    sc_trace(mVcdFile, ap_block_pp1_stage0_01001, "ap_block_pp1_stage0_01001");
    sc_trace(mVcdFile, rows_V_fu_341_p0, "rows_V_fu_341_p0");
    sc_trace(mVcdFile, cols_V_fu_345_p0, "cols_V_fu_345_p0");
    sc_trace(mVcdFile, tmp_user_V_fu_349_p1, "tmp_user_V_fu_349_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
    sc_trace(mVcdFile, ap_condition_582, "ap_condition_582");
#endif

    }
}

AXIvideo2Mat::~AXIvideo2Mat() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void AXIvideo2Mat::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_data_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_out.read()))) {
            AXI_video_strm_V_data_V_0_sel_rd =  (sc_logic) (~AXI_video_strm_V_data_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_data_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_in.read()))) {
            AXI_video_strm_V_data_V_0_sel_wr =  (sc_logic) (~AXI_video_strm_V_data_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_data_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_3)) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_2)))) {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_3)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_1)))) {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_2)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_1)) || 
                    (esl_seteq<1,2,2>(AXI_video_strm_V_data_V_0_state.read(), ap_const_lv2_3) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_ack_out.read()))))) {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_data_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_dest_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_dest_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_dest_V_0_state.read())))) {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_dest_V_0_state.read())))) {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_dest_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_dest_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_dest_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_dest_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_dest_V_0_ack_out.read()))))) {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_dest_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_last_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_out.read()))) {
            AXI_video_strm_V_last_V_0_sel_rd =  (sc_logic) (~AXI_video_strm_V_last_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_last_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_in.read()))) {
            AXI_video_strm_V_last_V_0_sel_wr =  (sc_logic) (~AXI_video_strm_V_last_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_last_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_last_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_last_V_0_state.read())))) {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_last_V_0_state.read())))) {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_last_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_last_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_last_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_last_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_ack_out.read()))))) {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_last_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_user_V_0_sel_rd = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_out.read()))) {
            AXI_video_strm_V_user_V_0_sel_rd =  (sc_logic) (~AXI_video_strm_V_user_V_0_sel_rd.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_user_V_0_sel_wr = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_in.read()))) {
            AXI_video_strm_V_user_V_0_sel_wr =  (sc_logic) (~AXI_video_strm_V_user_V_0_sel_wr.read());
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        AXI_video_strm_V_user_V_0_state = ap_const_lv2_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_vld_in.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_user_V_0_state.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_vld_in.read()) && 
              esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_user_V_0_state.read())))) {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_2;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_user_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_user_V_0_state.read())))) {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_2, AXI_video_strm_V_user_V_0_state.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()) && 
                     esl_seteq<1,2,2>(ap_const_lv2_1, AXI_video_strm_V_user_V_0_state.read())) || 
                    (esl_seteq<1,2,2>(ap_const_lv2_3, AXI_video_strm_V_user_V_0_state.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_ack_out.read())) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_user_V_0_vld_in.read()) && esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_ack_out.read()))))) {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_3;
        } else {
            AXI_video_strm_V_user_V_0_state = ap_const_lv2_2;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_358_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_358_p2.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state5.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state5.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_358_p2.read()))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        axi_data_V_0_i_reg_205 = tmp_data_V_reg_404.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        axi_data_V_0_i_reg_205 = axi_data_V_3_i_reg_309.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        axi_data_V_1_i_reg_237 = p_Val2_s_reg_284.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_358_p2.read()))) {
        axi_data_V_1_i_reg_237 = axi_data_V_0_i_reg_205.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        axi_data_V_3_i_reg_309 = axi_data_V_1_i_reg_237.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
        axi_data_V_3_i_reg_309 = AXI_video_strm_V_data_V_0_data_out.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        axi_last_V_0_i_reg_195 = tmp_last_V_reg_412.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        axi_last_V_0_i_reg_195 = axi_last_V_3_i_reg_297.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_582.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, or_ln76_fu_383_p2.read()))) {
            axi_last_V_2_i_reg_271 = ap_phi_mux_eol_phi_fu_229_p4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, or_ln76_fu_383_p2.read()))) {
            axi_last_V_2_i_reg_271 = AXI_video_strm_V_last_V_0_data_out.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            axi_last_V_2_i_reg_271 = ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_271.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        axi_last_V_3_i_reg_297 = eol_reg_226.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
        axi_last_V_3_i_reg_297 = AXI_video_strm_V_last_V_0_data_out.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        eol_0_i_reg_259 = axi_last_V_2_i_reg_271.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_358_p2.read()))) {
        eol_0_i_reg_259 = ap_const_lv1_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        eol_2_i_reg_321 = eol_0_i_reg_259.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
                !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
        eol_2_i_reg_321 = AXI_video_strm_V_last_V_0_data_out.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        eol_reg_226 = axi_last_V_2_i_reg_271.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_358_p2.read()))) {
        eol_reg_226 = axi_last_V_0_i_reg_195.read();
    }
    if (esl_seteq<1,1,1>(ap_condition_582.read(), ap_const_boolean_1)) {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, or_ln76_fu_383_p2.read()))) {
            p_Val2_s_reg_284 = ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, or_ln76_fu_383_p2.read()))) {
            p_Val2_s_reg_284 = AXI_video_strm_V_data_V_0_data_out.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            p_Val2_s_reg_284 = ap_phi_reg_pp1_iter0_p_Val2_s_reg_284.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        sof_1_i_fu_138 = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sof_1_i_fu_138 = ap_const_lv1_1;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        t_V_2_reg_248 = j_V_fu_374_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln71_fu_358_p2.read()))) {
        t_V_2_reg_248 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        t_V_reg_215 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        t_V_reg_215 = i_V_reg_428.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_load_A.read())) {
        AXI_video_strm_V_data_V_0_payload_A = inStream_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_load_B.read())) {
        AXI_video_strm_V_data_V_0_payload_B = inStream_TDATA.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_load_A.read())) {
        AXI_video_strm_V_last_V_0_payload_A = inStream_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_load_B.read())) {
        AXI_video_strm_V_last_V_0_payload_B = inStream_TLAST.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_load_A.read())) {
        AXI_video_strm_V_user_V_0_payload_A = inStream_TUSER.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_load_B.read())) {
        AXI_video_strm_V_user_V_0_payload_B = inStream_TUSER.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read())))) {
        cols_V_reg_399 = cols_V_fu_345_p1.read();
        rows_V_reg_394 = rows_V_fu_341_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_V_reg_428 = i_V_fu_363_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln73_reg_433 = icmp_ln73_fu_369_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1))) {
        tmp_data_V_reg_404 = AXI_video_strm_V_data_V_0_data_out.read();
        tmp_last_V_reg_412 = AXI_video_strm_V_last_V_0_data_out.read();
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_ack_in() {
    AXI_video_strm_V_data_V_0_ack_in = AXI_video_strm_V_data_V_0_state.read()[1];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_data_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_data_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_data_V_0_sel.read())) {
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_B.read();
    } else {
        AXI_video_strm_V_data_V_0_data_out = AXI_video_strm_V_data_V_0_payload_A.read();
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_load_A() {
    AXI_video_strm_V_data_V_0_load_A = (AXI_video_strm_V_data_V_0_state_cmp_full.read() & ~AXI_video_strm_V_data_V_0_sel_wr.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_load_B() {
    AXI_video_strm_V_data_V_0_load_B = (AXI_video_strm_V_data_V_0_sel_wr.read() & AXI_video_strm_V_data_V_0_state_cmp_full.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_sel() {
    AXI_video_strm_V_data_V_0_sel = AXI_video_strm_V_data_V_0_sel_rd.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_state_cmp_full() {
    AXI_video_strm_V_data_V_0_state_cmp_full =  (sc_logic) ((!AXI_video_strm_V_data_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(AXI_video_strm_V_data_V_0_state.read() != ap_const_lv2_1))[0];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_vld_in() {
    AXI_video_strm_V_data_V_0_vld_in = inStream_TVALID.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_data_V_0_vld_out() {
    AXI_video_strm_V_data_V_0_vld_out = AXI_video_strm_V_data_V_0_state.read()[0];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_dest_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_dest_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_dest_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_dest_V_0_vld_in() {
    AXI_video_strm_V_dest_V_0_vld_in = inStream_TVALID.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_ack_in() {
    AXI_video_strm_V_last_V_0_ack_in = AXI_video_strm_V_last_V_0_state.read()[1];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_last_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_last_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_last_V_0_sel.read())) {
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_B.read();
    } else {
        AXI_video_strm_V_last_V_0_data_out = AXI_video_strm_V_last_V_0_payload_A.read();
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_load_A() {
    AXI_video_strm_V_last_V_0_load_A = (AXI_video_strm_V_last_V_0_state_cmp_full.read() & ~AXI_video_strm_V_last_V_0_sel_wr.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_load_B() {
    AXI_video_strm_V_last_V_0_load_B = (AXI_video_strm_V_last_V_0_sel_wr.read() & AXI_video_strm_V_last_V_0_state_cmp_full.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_sel() {
    AXI_video_strm_V_last_V_0_sel = AXI_video_strm_V_last_V_0_sel_rd.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_state_cmp_full() {
    AXI_video_strm_V_last_V_0_state_cmp_full =  (sc_logic) ((!AXI_video_strm_V_last_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(AXI_video_strm_V_last_V_0_state.read() != ap_const_lv2_1))[0];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_vld_in() {
    AXI_video_strm_V_last_V_0_vld_in = inStream_TVALID.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_last_V_0_vld_out() {
    AXI_video_strm_V_last_V_0_vld_out = AXI_video_strm_V_last_V_0_state.read()[0];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_ack_in() {
    AXI_video_strm_V_user_V_0_ack_in = AXI_video_strm_V_user_V_0_state.read()[1];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_ack_out() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && 
          !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0)))) {
        AXI_video_strm_V_user_V_0_ack_out = ap_const_logic_1;
    } else {
        AXI_video_strm_V_user_V_0_ack_out = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_data_out() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, AXI_video_strm_V_user_V_0_sel.read())) {
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_B.read();
    } else {
        AXI_video_strm_V_user_V_0_data_out = AXI_video_strm_V_user_V_0_payload_A.read();
    }
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_load_A() {
    AXI_video_strm_V_user_V_0_load_A = (AXI_video_strm_V_user_V_0_state_cmp_full.read() & ~AXI_video_strm_V_user_V_0_sel_wr.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_load_B() {
    AXI_video_strm_V_user_V_0_load_B = (AXI_video_strm_V_user_V_0_sel_wr.read() & AXI_video_strm_V_user_V_0_state_cmp_full.read());
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_sel() {
    AXI_video_strm_V_user_V_0_sel = AXI_video_strm_V_user_V_0_sel_rd.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_state_cmp_full() {
    AXI_video_strm_V_user_V_0_state_cmp_full =  (sc_logic) ((!AXI_video_strm_V_user_V_0_state.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(AXI_video_strm_V_user_V_0_state.read() != ap_const_lv2_1))[0];
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_vld_in() {
    AXI_video_strm_V_user_V_0_vld_in = inStream_TVALID.read();
}

void AXIvideo2Mat::thread_AXI_video_strm_V_user_V_0_vld_out() {
    AXI_video_strm_V_user_V_0_vld_out = AXI_video_strm_V_user_V_0_state.read()[0];
}

void AXIvideo2Mat::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[4];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void AXIvideo2Mat::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[7];
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0_01001() {
    ap_block_pp1_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_V_full_n.read())));
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_V_full_n.read())));
}

void AXIvideo2Mat::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_V_full_n.read())));
}

void AXIvideo2Mat::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read()));
}

void AXIvideo2Mat::thread_ap_block_state5_pp1_stage0_iter0() {
    ap_block_state5_pp1_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op65_read_state5.read()));
}

void AXIvideo2Mat::thread_ap_block_state6_pp1_stage0_iter1() {
    ap_block_state6_pp1_stage0_iter1 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && esl_seteq<1,1,1>(ap_const_logic_0, img_data_stream_V_full_n.read()));
}

void AXIvideo2Mat::thread_ap_block_state8() {
    ap_block_state8 = (esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read()));
}

void AXIvideo2Mat::thread_ap_condition_582() {
    ap_condition_582 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0));
}

void AXIvideo2Mat::thread_ap_condition_pp1_exit_iter0_state5() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_369_p2.read())) {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state5 = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_358_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void AXIvideo2Mat::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void AXIvideo2Mat::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()))) {
        ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4 = p_Val2_s_reg_284.read();
    } else {
        ap_phi_mux_axi_data_V_1_i_phi_fu_240_p4 = axi_data_V_1_i_reg_237.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_eol_0_i_phi_fu_263_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()))) {
        ap_phi_mux_eol_0_i_phi_fu_263_p4 = axi_last_V_2_i_reg_271.read();
    } else {
        ap_phi_mux_eol_0_i_phi_fu_263_p4 = eol_0_i_reg_259.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_mux_eol_2_i_phi_fu_324_p4() {
    ap_phi_mux_eol_2_i_phi_fu_324_p4 = eol_2_i_reg_321.read();
}

void AXIvideo2Mat::thread_ap_phi_mux_eol_phi_fu_229_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()))) {
        ap_phi_mux_eol_phi_fu_229_p4 = axi_last_V_2_i_reg_271.read();
    } else {
        ap_phi_mux_eol_phi_fu_229_p4 = eol_reg_226.read();
    }
}

void AXIvideo2Mat::thread_ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_271() {
    ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_271 =  (sc_lv<1>) ("X");
}

void AXIvideo2Mat::thread_ap_phi_reg_pp1_iter0_p_Val2_s_reg_284() {
    ap_phi_reg_pp1_iter0_p_Val2_s_reg_284 = "XXXXXXXX";
}

void AXIvideo2Mat::thread_ap_predicate_op65_read_state5() {
    ap_predicate_op65_read_state5 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, or_ln76_fu_383_p2.read()));
}

void AXIvideo2Mat::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void AXIvideo2Mat::thread_cols_V_fu_345_p0() {
    cols_V_fu_345_p0 = img_cols_V_dout.read();
}

void AXIvideo2Mat::thread_cols_V_fu_345_p1() {
    cols_V_fu_345_p1 = esl_sext<32,11>(cols_V_fu_345_p0.read());
}

void AXIvideo2Mat::thread_i_V_fu_363_p2() {
    i_V_fu_363_p2 = (!t_V_reg_215.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_215.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void AXIvideo2Mat::thread_icmp_ln71_fu_358_p2() {
    icmp_ln71_fu_358_p2 = (!t_V_reg_215.read().is_01() || !rows_V_reg_394.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_215.read() == rows_V_reg_394.read());
}

void AXIvideo2Mat::thread_icmp_ln73_fu_369_p2() {
    icmp_ln73_fu_369_p2 = (!t_V_2_reg_248.read().is_01() || !cols_V_reg_399.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_2_reg_248.read() == cols_V_reg_399.read());
}

void AXIvideo2Mat::thread_img_cols_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_cols_V_blk_n = img_cols_V_empty_n.read();
    } else {
        img_cols_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_cols_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_cols_V_out_blk_n = img_cols_V_out_full_n.read();
    } else {
        img_cols_V_out_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_cols_V_out_din() {
    img_cols_V_out_din = img_cols_V_dout.read();
}

void AXIvideo2Mat::thread_img_cols_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read())))) {
        img_cols_V_out_write = ap_const_logic_1;
    } else {
        img_cols_V_out_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_img_cols_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read())))) {
        img_cols_V_read = ap_const_logic_1;
    } else {
        img_cols_V_read = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_img_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()))) {
        img_data_stream_V_blk_n = img_data_stream_V_full_n.read();
    } else {
        img_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_data_stream_V_din() {
    img_data_stream_V_din = p_Val2_s_reg_284.read();
}

void AXIvideo2Mat::thread_img_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_reg_433.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        img_data_stream_V_write = ap_const_logic_1;
    } else {
        img_data_stream_V_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_img_rows_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_rows_V_blk_n = img_rows_V_empty_n.read();
    } else {
        img_rows_V_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_rows_V_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        img_rows_V_out_blk_n = img_rows_V_out_full_n.read();
    } else {
        img_rows_V_out_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_img_rows_V_out_din() {
    img_rows_V_out_din = img_rows_V_dout.read();
}

void AXIvideo2Mat::thread_img_rows_V_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read())))) {
        img_rows_V_out_write = ap_const_logic_1;
    } else {
        img_rows_V_out_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_img_rows_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read())))) {
        img_rows_V_read = ap_const_logic_1;
    } else {
        img_rows_V_read = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_inStream_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_369_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, or_ln76_fu_383_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read())))) {
        inStream_TDATA_blk_n = AXI_video_strm_V_data_V_0_state.read()[0];
    } else {
        inStream_TDATA_blk_n = ap_const_logic_1;
    }
}

void AXIvideo2Mat::thread_inStream_TREADY() {
    inStream_TREADY = AXI_video_strm_V_dest_V_0_state.read()[1];
}

void AXIvideo2Mat::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_358_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_j_V_fu_374_p2() {
    j_V_fu_374_p2 = (!t_V_2_reg_248.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_2_reg_248.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void AXIvideo2Mat::thread_or_ln76_fu_383_p2() {
    or_ln76_fu_383_p2 = (sof_1_i_fu_138.read() | ap_phi_mux_eol_0_i_phi_fu_263_p4.read());
}

void AXIvideo2Mat::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void AXIvideo2Mat::thread_rows_V_fu_341_p0() {
    rows_V_fu_341_p0 = img_rows_V_dout.read();
}

void AXIvideo2Mat::thread_rows_V_fu_341_p1() {
    rows_V_fu_341_p1 = esl_sext<32,11>(rows_V_fu_341_p0.read());
}

void AXIvideo2Mat::thread_start_out() {
    start_out = real_start.read();
}

void AXIvideo2Mat::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void AXIvideo2Mat::thread_tmp_user_V_fu_349_p1() {
    tmp_user_V_fu_349_p1 = AXI_video_strm_V_user_V_0_data_out.read();
}

void AXIvideo2Mat::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_rows_V_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_cols_V_out_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_user_V_fu_349_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(AXI_video_strm_V_data_V_0_vld_out.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_user_V_fu_349_p1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln71_fu_358_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 16 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_369_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_369_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && !(esl_seteq<1,1,1>(ap_const_lv1_0, eol_2_i_reg_321.read()) && esl_seteq<1,1,1>(ap_const_logic_0, AXI_video_strm_V_data_V_0_vld_out.read())) && esl_seteq<1,1,1>(ap_const_lv1_1, ap_phi_mux_eol_2_i_phi_fu_324_p4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

